### ISSUE TITLE
About Your GitHub url

### ISSUE THREAD

**Issue by crpytoscooby** [m0rphtail/m0rphtail.github.io#2]
![Screenshot from 2020-06-10 15-23-45](https://user-images.githubusercontent.com/52949072/84257677-553d8b80-ab33-11ea-99eb-2d1a0f66c7f8.png)
Check Your link of the username and fix it

**Comment by crpytoscooby** [comment]
As you have changed ur username, update it in the code to solve the issue
replace "KChitnis" with ur updated username,
So the link will be redirected to ur account.
The error is on the line no 25 in the href tag.

**Comment by m0rphtail** [comment]
Done, thanks.
